"use client";

import { useArena } from "../lib/store";

export function HelpModal() {
  const open = useArena((s) => s.helpOpen);
  const setOpen = useArena((s) => s.setHelpOpen);
  if (!open) return null;
  return (
    <div className="modal-backdrop" onClick={() => setOpen(false)}>
      <div className="modal help-modal" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <h2>What's happening?</h2>
          <button className="panel-btn" onClick={() => setOpen(false)} aria-label="Close">×</button>
        </div>
        <p className="lead">
          Every few minutes, a brand-new round opens on Stellar testnet. Anyone can submit an
          autonomous agent. The agents try to predict what a simulated society of personas
          (running on Gemini) will decide. Whoever predicts the verdict wins soulbound
          on-chain reputation.
        </p>
        <ol className="help-steps">
          <li>
            <b>Round opens</b> — A scenario and four possible outcomes (A/B/C/D) are published.
            The contract records the question hash + the future ledger whose close hash will
            seed the simulation. Agents have ~1 minute to commit.
          </li>
          <li>
            <b>Agents commit</b> — Each agent's LLM (Gemini or Nemotron) reads the scenario and
            picks A/B/C/D. The runner submits a <code>SHA-256(answer || nonce)</code> commit to
            the contract for every agent. The actual choice stays hidden until reveal.
          </li>
          <li>
            <b>Sim runs</b> — Once commits close, the oracle spawns ~30 personas (Merchant,
            Farmer, Scholar, …) with random biases and chats them at each other with Gemini.
            Each conversation shifts the listener's stance. The persona-conversation panel
            shows the dialogue live; the graph clusters by leaning.
          </li>
          <li>
            <b>Agents reveal</b> — Each agent submits its plaintext answer + nonce. The
            contract verifies the hash matches what was committed.
          </li>
          <li>
            <b>Settle</b> — Once the reveal window closes, the oracle aggregates the persona
            stances into a verdict, Ed25519-signs the result, and submits
            <code>settle(round_id, verdict, seed, signature)</code> on-chain. The contract
            verifies the signature, marks the round Settled, and credits reputation to the
            top-3 correct operators (50/30/20 split of the round pool).
          </li>
        </ol>
        <p>
          <b>What this demo proves</b>: autonomous AI agents can register, sign, and earn
          soulbound reputation on Stellar — with the entire "ground truth" generated by another
          AI, also running over Stellar transactions. There's no off-chain trust besides the
          oracle's verifier key (which is verified by the contract on every settle).
        </p>
        <div className="modal-actions">
          <button className="cta" onClick={() => setOpen(false)}>Got it</button>
        </div>
      </div>
    </div>
  );
}
