"use client";

import { useEffect, useMemo, useState } from "react";
import { useArena, ORACLE } from "../lib/store";
import type {
  AgentReveal,
  AgentSubmission,
  PersonaMessage,
  TxEvent,
} from "@mirofish/shared";

const CHOICES = ["A", "B", "C", "D"] as const;
const CONTRACT = process.env.NEXT_PUBLIC_LIVE_ROUND_CONTRACT_ID ?? "";

interface RoundDetail {
  round: {
    roundId: number;
    templateId: string;
    scenario: string;
    options: Record<"A" | "B" | "C" | "D", string>;
    tags: string[];
    openedAt: string;
    closesAt: string;
    resolvesAt: string;
    seedLedger: number;
    questionHash: string;
    seed: string | null;
    verdict: string | null;
    confidence: number | null;
    distribution: Record<"A" | "B" | "C" | "D", number> | null;
    signature: string | null;
    oraclePubkey: string | null;
    resolvedAt: string | null;
    aiSummary: string | null;
    state: string;
  };
  messages: PersonaMessage[];
  commits: AgentSubmission[];
  reveals: AgentReveal[];
  txs: TxEvent[];
}

function short(s: string, head = 6, tail = 4): string {
  if (!s) return "";
  if (s.length <= head + tail + 1) return s;
  return `${s.slice(0, head)}…${s.slice(-tail)}`;
}

export function RoundDetailModal() {
  const summary = useArena((s) => s.detailRound);
  const setDetailRound = useArena((s) => s.setDetailRound);
  const [detail, setDetail] = useState<RoundDetail | null>(null);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    if (!summary) {
      setDetail(null);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setErr(null);
    const load = (): Promise<void> =>
      fetch(`${ORACLE}/rounds/${summary.roundId}`)
        .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
        .then((j: RoundDetail) => {
          if (cancelled) return;
          setDetail(j);
          // If the AI summary hasn't landed yet, refetch in 4s.
          if (!j.round.aiSummary && (j.round.state === "resolved" || j.round.state === "settled")) {
            setTimeout(load, 4000);
          }
        })
        .catch((e) => {
          if (!cancelled) setErr((e as Error).message);
        })
        .finally(() => {
          if (!cancelled) setLoading(false);
        });
    load();
    return () => {
      cancelled = true;
    };
  }, [summary]);

  if (!summary) return null;

  return (
    <div className="modal-backdrop" onClick={() => setDetailRound(null)}>
      <div
        className="modal help-modal round-detail-modal"
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 10 }}>
          <div>
            <h2 style={{ margin: 0 }}>Round #{summary.roundId}</h2>
            <p style={{ margin: "2px 0 0", color: "var(--fg-dim)", fontSize: 12 }}>
              {summary.templateId} · {summary.txCount} tx ·{" "}
              {summary.correct}/{summary.revealed} correct
            </p>
          </div>
          <button className="panel-btn" onClick={() => setDetailRound(null)} aria-label="Close">×</button>
        </div>

        {loading && <p className="empty">Loading…</p>}
        {err && <p style={{ color: "var(--bad)", fontSize: 12 }}>Couldn't load round detail: {err}</p>}

        {detail && <RoundBody detail={detail} />}

        <div className="modal-actions">
          <button className="cta" onClick={() => setDetailRound(null)}>Close</button>
        </div>
      </div>
    </div>
  );
}

function RoundBody({ detail }: { detail: RoundDetail }) {
  const r = detail.round;
  // All sections open by default — the user wants the full picture without
  // hunting around. We still allow toggling individual sections closed.
  const [closed, setClosed] = useState<Set<string>>(new Set());
  const isOpen = (s: string) => !closed.has(s);
  const toggle = (s: string) =>
    setClosed((prev) => {
      const next = new Set(prev);
      if (next.has(s)) next.delete(s);
      else next.add(s);
      return next;
    });

  const verdict = r.verdict as "A" | "B" | "C" | "D" | null;
  const personaIds = useMemo(() => {
    const set = new Set<string>();
    for (const m of detail.messages) {
      set.add(m.from);
      set.add(m.to);
    }
    return [...set].sort();
  }, [detail.messages]);

  return (
    <>
      {/* AI summary — generated on settle */}
      {(r.aiSummary || r.state === "resolved" || r.state === "settled") && (
        <div className="ai-summary">
          <div className="ai-summary-head">
            <span className="ai-summary-badge">AI summary</span>
            <span style={{ color: "var(--fg-dim)", fontSize: 11 }}>
              Generated by Gemini at round resolve
            </span>
          </div>
          {r.aiSummary ? (
            <p className="ai-summary-text">{r.aiSummary}</p>
          ) : (
            <p className="ai-summary-pending">Generating summary…</p>
          )}
        </div>
      )}

      {/* Scenario + options */}
      <Section
        title="Scenario & outcome"
        open={isOpen("scenario")}
        onToggle={() => toggle("scenario")}
      >
        <div className="agent-prompt">{r.scenario}</div>
        <div className="round-card-options" style={{ marginTop: 10 }}>
          {CHOICES.map((k) => {
            const isVerdict = verdict === k;
            const conf = r.distribution?.[k];
            return (
              <div className={`round-card-option ${isVerdict ? "winner" : ""}`} key={k}>
                <span className={`key ${k}`}>{k}</span>
                <span style={{ flex: 1 }}>{r.options[k]}</span>
                {conf !== undefined && (
                  <span className="round-card-conf">{(conf * 100).toFixed(1)}%</span>
                )}
              </div>
            );
          })}
        </div>
        {verdict && (
          <div className="round-card-verdict" style={{ marginTop: 10 }}>
            MiroFish verdict: <span className={`key ${verdict}`}>{verdict}</span>
            <span style={{ marginLeft: 8, color: "var(--fg-dim)", fontSize: 12 }}>
              {(r.confidence ?? 0) * 100 > 0 ? `${((r.confidence ?? 0) * 100).toFixed(1)}% confidence` : ""}
            </span>
          </div>
        )}
        <div className="round-detail-meta">
          <KV label="State" value={r.state} />
          <KV label="Opened" value={new Date(r.openedAt).toLocaleString()} />
          <KV label="Resolves" value={new Date(r.resolvesAt).toLocaleString()} />
          {r.resolvedAt && <KV label="Resolved" value={new Date(r.resolvedAt).toLocaleString()} />}
          <KV
            label="Seed ledger"
            value={
              <a
                href={`https://stellar.expert/explorer/testnet/ledger/${r.seedLedger}`}
                target="_blank"
                rel="noreferrer"
              >
                {r.seedLedger}
              </a>
            }
          />
          {r.seed && (
            <KV label="Seed hash" value={<code>{short(r.seed, 10, 6)}</code>} />
          )}
          {r.oraclePubkey && (
            <KV label="Oracle pubkey" value={<code>{short(r.oraclePubkey, 8, 6)}</code>} />
          )}
          {r.signature && (
            <KV label="Verdict signature" value={<code>{short(r.signature, 8, 8)}</code>} />
          )}
        </div>
      </Section>

      {/* Agent commits & reveals */}
      <Section
        title={`Agents (${detail.commits.length} committed · ${detail.reveals.length} revealed)`}
        open={isOpen("agents")}
        onToggle={() => toggle("agents")}
      >
        {detail.commits.length === 0 ? (
          <p className="empty">No agent activity recorded for this round.</p>
        ) : (
          <div className="round-detail-agents">
            {detail.commits.map((c) => {
              const reveal = detail.reveals.find((r2) => r2.agent === c.agent);
              const correct = verdict && reveal?.answer === verdict;
              return (
                <div key={c.agent} className="round-detail-agent-row">
                  <div className="round-detail-agent-head">
                    <a
                      href={`https://stellar.expert/explorer/testnet/account/${c.agent}`}
                      target="_blank"
                      rel="noreferrer"
                      className="round-detail-agent-name"
                    >
                      {short(c.agent, 6, 4)}
                    </a>
                    {reveal ? (
                      <>
                        <span className={`key ${reveal.answer}`}>{reveal.answer}</span>
                        {verdict && (
                          <span className={`reveal-score ${correct ? "good" : "bad"}`}>
                            {correct ? "✓" : "✗"}
                          </span>
                        )}
                      </>
                    ) : (
                      <span className="reveal-pending">committed · no reveal</span>
                    )}
                  </div>
                  {reveal?.reasoning && (
                    <p className="reveal-reasoning">{reveal.reasoning}</p>
                  )}
                  <div className="round-detail-tx-links">
                    {c.commitTx && (
                      <a
                        href={`https://stellar.expert/explorer/testnet/tx/${c.commitTx}`}
                        target="_blank"
                        rel="noreferrer"
                      >
                        commit ↗
                      </a>
                    )}
                    {reveal?.revealTx && (
                      <a
                        href={`https://stellar.expert/explorer/testnet/tx/${reveal.revealTx}`}
                        target="_blank"
                        rel="noreferrer"
                      >
                        reveal ↗
                      </a>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </Section>

      {/* Persona conversations */}
      <Section
        title={`Persona conversations (${detail.messages.length} msgs · ${personaIds.length} personas)`}
        open={isOpen("conversations")}
        onToggle={() => toggle("conversations")}
      >
        {detail.messages.length === 0 ? (
          <p className="empty">No persona dialogue recorded for this round.</p>
        ) : (
          <div className="round-detail-msgs">
            {detail.messages.map((m) => (
              <div className="conversation-item" key={`${m.roundId}-${m.seq}`}>
                <div className="meta">
                  <span className="from">{m.from}</span>
                  <span className="arrow">→</span>
                  <span className="to">{m.to}</span>
                  <span style={{ marginLeft: "auto", color: "var(--fg-dim)" }}>
                    tick {m.tick}
                  </span>
                </div>
                <div>{m.content}</div>
              </div>
            ))}
          </div>
        )}
      </Section>

      {/* Transactions */}
      <Section
        title={`Stellar transactions (${detail.txs.length})`}
        open={isOpen("txs")}
        onToggle={() => toggle("txs")}
      >
        {detail.txs.length === 0 ? (
          <p className="empty">No transactions recorded for this round.</p>
        ) : (
          <div className="round-detail-txs">
            {detail.txs.map((t) => (
              <a
                key={t.hash}
                href={`https://stellar.expert/explorer/testnet/tx/${t.hash}`}
                target="_blank"
                rel="noreferrer"
                className="tx-item tx-link"
              >
                <span className={`tx-kind ${t.kind}`}>{t.kind.replace("_", " ")}</span>
                <span className="tx-label">{t.label ?? ""}</span>
                <span className="tx-hash">{short(t.hash, 6, 4)}</span>
              </a>
            ))}
          </div>
        )}
      </Section>

      {CONTRACT && (
        <p style={{ marginTop: 12, color: "var(--fg-dim)", fontSize: 11 }}>
          On-chain canonical state:{" "}
          <a
            href={`https://stellar.expert/explorer/testnet/contract/${CONTRACT}`}
            target="_blank"
            rel="noreferrer"
            style={{ color: "var(--fg-dim)", textDecoration: "underline" }}
          >
            {short(CONTRACT, 10, 6)}
          </a>{" "}
          ·{" "}
          <code>
            stellar contract invoke … get_round --round_id {r.roundId}
          </code>
        </p>
      )}
    </>
  );
}

function Section({
  title,
  open,
  onToggle,
  children,
}: {
  title: string;
  open: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="round-detail-section">
      <button className="round-detail-section-head" onClick={onToggle} type="button">
        <span style={{ width: 14, display: "inline-block" }}>{open ? "▾" : "▸"}</span>
        <span>{title}</span>
      </button>
      {open && <div className="round-detail-section-body">{children}</div>}
    </div>
  );
}

function KV({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="kv-row">
      <span className="kv-label">{label}</span>
      <span className="kv-value">{value}</span>
    </div>
  );
}
