"use client";

import { useArena } from "../lib/store";

export function WorldModal() {
  const open = useArena((s) => s.worldOpen);
  const setOpen = useArena((s) => s.setWorldOpen);
  const world = useArena((s) => s.world);
  if (!open) return null;

  return (
    <div className="modal-backdrop" onClick={() => setOpen(false)}>
      <div className="modal help-modal world-modal" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 12 }}>
          <div>
            <h2 style={{ margin: 0 }}>The world so far</h2>
            <p style={{ margin: "4px 0 0", color: "var(--fg-dim)", fontSize: 12 }}>
              {world?.settledCount ?? 0} settled rounds · this reality is the cumulative
              outcome of every simulator verdict in order.
            </p>
          </div>
          <button className="panel-btn" onClick={() => setOpen(false)} aria-label="Close">×</button>
        </div>

        {!world ? (
          <p className="empty">Loading…</p>
        ) : world.settledCount === 0 ? (
          <p className="empty">
            Round 1 hasn't settled yet. Once it does, you'll see the running state of the
            kale-farming world build out here, round by round.
          </p>
        ) : (
          <>
            <div className="world-narrative">
              {world.narrative ? (
                <p>{world.narrative}</p>
              ) : (
                <p className="empty">Generating the running narrative…</p>
              )}
            </div>

            <div className="world-events">
              <div className="world-events-head">
                Event timeline ({world.events.length})
              </div>
              {world.events.map((e) => (
                <div className="world-event" key={e.roundId}>
                  <div className="world-event-head">
                    <span className="world-event-id">Round #{e.roundId}</span>
                    <span className={`key ${e.verdict}`}>{e.verdict}</span>
                    <span className="world-event-tag">{e.templateId}</span>
                  </div>
                  <p className="world-event-outcome">{e.outcome}</p>
                </div>
              ))}
            </div>
          </>
        )}

        {world?.generatedAt && (
          <p style={{ marginTop: 14, color: "var(--fg-dim)", fontSize: 11 }}>
            Narrative generated by Gemini Flash Lite at {new Date(world.generatedAt).toLocaleString()}.
            Auto-refreshes every 3 settled rounds.
          </p>
        )}

        <div className="modal-actions">
          <button className="cta" onClick={() => setOpen(false)}>Close</button>
        </div>
      </div>
    </div>
  );
}
